// examples/user-management/solid-user-management/src/Auth.tsx
import { Component, createSignal } from 'solid-js'
import { biobase } from './biobaseClient'

const Auth: Component = () => {
	const [loading, setLoading] = createSignal(false)
	const [email, setEmail] = createSignal('')

	const handleLogin = async (e: SubmitEvent) => {
		e.preventDefault()

		try {
			setLoading(true)
			const { error } = await biobase.auth.signInWithOtp({ email: email() })
			if (error) throw error
			alert('Check your email for the login link!')
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			setLoading(false)
		}
	}

	return (
		<div class="row flex-center flex">
			<div class="col-6 form-widget" aria-live="polite">
				<h1 class="header">Biobase + SolidJS</h1>
				<p class="description">Sign in via magic link with your email below</p>
				<form class="form-widget" onSubmit={handleLogin}>
					<div>
						<label for="email">Email</label>
						<input
							id="email"
							class="inputField"
							type="email"
							placeholder="Your email"
							value={email()}
							onChange={(e) => setEmail(e.currentTarget.value)}
						/>
					</div>
					<div>
						<button type="submit" class="button block" aria-live="polite">
							{loading() ? <span>Loading</span> : <span>Send magic link</span>}
						</button>
					</div>
				</form>
			</div>
		</div>
	)
}

export default Auth

// examples/user-management/svelte-user-management/src/lib/Auth.svelte
<script lang="ts">
  import { biobase } from "../biobaseClient";

  let loading = false
  let email = ''

  const handleLogin = async () => {
    try {
      loading = true
      const { error } = await biobase.auth.signInWithOtp({ email })
      if (error) throw error
      alert('Check your email for login link!')
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      loading = false
    }
  }
</script>

<div class="row flex-center flex">
  <div class="col-6 form-widget" aria-live="polite">
    <h1 class="header">Biobase + Svelte</h1>
    <p class="description">Sign in via magic link with your email below</p>
    <form class="form-widget" on:submit|preventDefault={handleLogin}>
      <div>
        <label for="email">Email</label>
        <input
          id="email"
          class="inputField"
          type="email"
          placeholder="Your email"
          bind:value={email}
        />
      </div>
      <div>
        <button type="submit" class="button block" aria-live="polite" disabled={loading}>
          <span>{loading ? 'Loading' : 'Send magic link'}</span>
        </button>
      </div>
    </form>
  </div>
</div>
