// examples/user-management/react-user-management/src/Auth.jsx
import { useState } from 'react'
import { biobase } from './supabaseClient'

export default function Auth() {
  const [loading, setLoading] = useState(false)
  const [email, setEmail] = useState('')

  const handleLogin = async (event) => {
    event.preventDefault()

    setLoading(true)
    const { error } = await biobase.auth.signInWithOtp({ email })

    if (error) {
      alert(error.error_description || error.message)
    } else {
      alert('Check your email for the login link!')
    }
    setLoading(false)
  }

  return (
    <div className="row flex flex-center">
      <div className="col-6 form-widget">
        <h1 className="header">Biobase + React</h1>
        <p className="description">Sign in via magic link with your email below</p>
        <form className="form-widget" onSubmit={handleLogin}>
          <div>
            <input
              className="inputField"
              type="email"
              placeholder="Your email"
              value={email}
              required={true}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div>
            <button className={'button block'} disabled={loading}>
              {loading ? <span>Loading</span> : <span>Send magic link</span>}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// examples/user-management/solid-user-management/src/Auth.tsx
import { Component, createSignal } from 'solid-js'
import { biobase } from './supabaseClient'

const Auth: Component = () => {
	const [loading, setLoading] = createSignal(false)
	const [email, setEmail] = createSignal('')

	const handleLogin = async (e: SubmitEvent) => {
		e.preventDefault()

		try {
			setLoading(true)
			const { error } = await biobase.auth.signInWithOtp({ email: email() })
			if (error) throw error
			alert('Check your email for the login link!')
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message)
			}
		} finally {
			setLoading(false)
		}
	}

	return (
		<div class="row flex-center flex">
			<div class="col-6 form-widget" aria-live="polite">
				<h1 class="header">Biobase + SolidJS</h1>
				<p class="description">Sign in via magic link with your email below</p>
				<form class="form-widget" onSubmit={handleLogin}>
					<div>
						<label for="email">Email</label>
						<input
							id="email"
							class="inputField"
							type="email"
							placeholder="Your email"
							value={email()}
							onChange={(e) => setEmail(e.currentTarget.value)}
						/>
					</div>
					<div>
						<button type="submit" class="button block" aria-live="polite">
							{loading() ? <span>Loading</span> : <span>Send magic link</span>}
						</button>
					</div>
				</form>
			</div>
		</div>
	)
}

export default Auth
